server:
  port: 8767

spring:
  application:
    name: eureka-client-one
  cloud:
    config:
      fail-fast: true
      name: ${spring.application.name}
      profile: ${spring.profiles.active}
      discovery:
        enabled: true
        service-id: spring-config
  profiles:
    active: prod
  main:
    allow-bean-definition-overriding: true
  boot:
     admin:
      client:
        url: http://localhost:8084

eureka:
  instance:
    hostname: localhost
    port: 8761
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/


feign:
 hystrix:
  enabled: true